name: jsoncheck

on:
  push:
    paths:                                  
      #- '**.json'
      - 'ToValidate/**'  #When JSON is added, the check process starts         
   
 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      #Checkout and token for connexion
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}


      - uses: Zingabopp/JsonValidate-Action@v1
        with:
          json-schema: Path/To/Your/Schema.json
          json-file: Path/To/Your/JsonFile.json
