name: jsoncheck

on:
  push:
    paths:                                  
      #- '**.json'
      #- 'ToValidate/**'  #When JSON is added, the check process starts   
      - .github/workflows/newAction.yml
   
 
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      #Checkout and token for connexion
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      #JSON file to validate check
      - uses: Zingabopp/JsonValidate-Action@v1
        with:
          json-schema: CorrectJSON/schema.json
          json-file: ToValidate/JSON.json
         
         
      #Delete old JSON.json in CorrectJSON/ (due to is not possible to overwrite) 
      - name: delete-old-CorrectJSON
        uses: JesseTG/rm@v1.0.2
        with:
          path: 'CorrectJSON/JSON.json' 
          
          
      #Move JSON validated from ToValidate folder to CorrectJSON folder 
      - name: move-to-CorrectJSON     
        run: git mv 'ToValidate/JSON.json' 'CorrectJSON/JSON.json'  
          
