name: jsoncheck

on:
  push:
    paths:                                  
      #- '**.json'
      #- 'ToValidate/**'  #When JSON is added, the check process starts   
      - .github/workflows/newAction.yml
   

 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      #Checkout and token for connexion
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      - uses: Zingabopp/JsonValidate-Action@v1
        with:
          json-schema: CorrectJSON/schema.json
          json-file: CorrectJSON/JSON.json
          
